# -*- coding: utf-8 -*-
"""finding_pixel_coord.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beLMJ5446bx6To6PnHtzKZJr2Sv5gNo-
"""

!pip install ipympl

from google.colab import output
output.enable_custom_widget_manager()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib ipympl

from google.colab import output
output.enable_custom_widget_manager()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
# %matplotlib ipympl
from google.colab.patches import cv2_imshow
import cv2

f1 = 'petal_54.jpg'

img = mpimg.imread(f1)

fig,ax = plt.subplots()
img1 = ax.imshow(img)

def onclick(event):
    ix, iy = event.xdata, event.ydata
    print(ix, iy)

cid = fig.canvas.mpl_connect('button_press_event', onclick)

